# Generated by Django 3.2.7 on 2021-09-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Detective', 'Детектив'), ('Thriller', 'Триллер'), ('Novel', 'Роман'), ('Psychology', 'Психолоия')], default='Detective', max_length=64, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, default='media/img.png', upload_to='books_img/%Y/%m/%d', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name_product',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='discount',
            field=models.BooleanField(default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(blank=True, default='Не определено', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='img',
            field=models.ImageField(blank=True, upload_to='seller_img/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='position',
            field=models.CharField(choices=[('Trainee', 'Стажер'), ('Salesman', 'Продавец'), ('Oldest salesman', 'Старший продавец'), ('Supervisor', 'Руководитель')], default='Trainee', max_length=64, verbose_name='Должность'),
        ),
    ]
